"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateContent = exports.createEvent = exports.listEvents = exports.writeSheet = exports.readSheet = exports.createFolder = exports.listFiles = exports.getEmail = exports.listEmails = exports.sendEmail = void 0;
var gmail_1 = require("./gmail");
Object.defineProperty(exports, "sendEmail", { enumerable: true, get: function () { return gmail_1.sendEmail; } });
Object.defineProperty(exports, "listEmails", { enumerable: true, get: function () { return gmail_1.listEmails; } });
Object.defineProperty(exports, "getEmail", { enumerable: true, get: function () { return gmail_1.getEmail; } });
var drive_1 = require("./drive");
Object.defineProperty(exports, "listFiles", { enumerable: true, get: function () { return drive_1.listFiles; } });
Object.defineProperty(exports, "createFolder", { enumerable: true, get: function () { return drive_1.createFolder; } });
var sheets_1 = require("./sheets");
Object.defineProperty(exports, "readSheet", { enumerable: true, get: function () { return sheets_1.readSheet; } });
Object.defineProperty(exports, "writeSheet", { enumerable: true, get: function () { return sheets_1.writeSheet; } });
var calendar_1 = require("./calendar");
Object.defineProperty(exports, "listEvents", { enumerable: true, get: function () { return calendar_1.listEvents; } });
Object.defineProperty(exports, "createEvent", { enumerable: true, get: function () { return calendar_1.createEvent; } });
var gemini_1 = require("./gemini");
Object.defineProperty(exports, "generateContent", { enumerable: true, get: function () { return gemini_1.generateContent; } });
